name: Build Expo APK

on:  
  push:  
    branches: [main]  
  pull_request:  
    branches: [main]  

jobs:  
  build:  
    runs-on: ubuntu-latest  

    steps:  
      - name: Checkout repository  
        uses: actions/checkout@v3  

      - name: Setup Node.js  
        uses: actions/setup-node@v3  
        with:  
          node-version: 18  

      - name: Install dependencies  
        run: npm install  

      - name: Install Expo CLI & EAS  
        run: npm install -g expo-cli eas-cli  

      - name: Authenticate with Expo  
        run: eas login --token ${{ secrets.EXPO_TOKEN }}  

      - name: Build APK  
        run: eas build --platform android --profile preview --non-interactive  

      - name: Upload APK Artifact  
        uses: actions/upload-artifact@v3  
        with:  
          name: expo-apk  
          path: build/*.apk
